export enum ResponseMessage {
    INVALID_CURRENT_PASSWORD = 'Invalid current password',
    INVALID_CONFIRM_PASSWORD = 'Confirm password should match with password',
    NOT_EXISTED_USER = 'Invalid user',
    SOMETHING_WRONG = 'Something went wrong',
    EMAIL_TAKEN = 'Email has been taken',
    INVALID_EMAIL_PASSWORD = 'Email or password is not correct',
    EMAIL_NOT_ACTIVE = 'Email is not active',
    INVALID_PHONE = 'Invalid phone number',
    INVALID_GENDER = 'Invalid gender',
    INVALID_PASSWORD = 'Invalid password',
    INVALID_IMAGE = 'Invalid image',
    UNAUTHORIZED = 'Sorry, your request could not be processed',
    NOT_FOUND = 'Page not found',
    DUPLICATED_PASSWORD = 'New password should not be same with current password',
    FORBIDDEN = 'Sorry, your request could not be processed',
    INVALID_CATEGORY = 'Invalid category',
    INVALID_STATUS = 'Invalid status',
    DUPLICATED_CATEGORY = 'This category has already existed',
    DUPLICATED_ORDER = 'Order has already existed',
    ACTION_NOT_ALLOW = 'This action is not allowed',
    INVALID_CATEGORIES = 'Invalid categories',
}
